# United Nations AQUASTAT

**OBJECTIVES**: 

- Full exploration of dataset

In [1]:
import pandas as pd

In [42]:
data = pd.read_csv('data/eda_data/aquastat.csv', index_col=0)

In [43]:
data.head()

,country,region,variable,variable_full,time_period,year_measured,value
0,Afghanistan,World | Asia,total_area,Total area of the country (1000 ha),1958-1962,1962.0,65286.0
1,Afghanistan,World | Asia,total_area,Total area of the country (1000 ha),1963-1967,1967.0,65286.0
2,Afghanistan,World | Asia,total_area,Total area of the country (1000 ha),1968-1972,1972.0,65286.0
3,Afghanistan,World | Asia,total_area,Total area of the country (1000 ha),1973-1977,1977.0,65286.0
4,Afghanistan,World | Asia,total_area,Total area of the country (1000 ha),1978-1982,1982.0,65286.0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143280 entries, 0 to 143279
Data columns (total 7 columns):
country          143280 non-null object
region           143280 non-null object
variable         143280 non-null object
variable_full    143280 non-null object
time_period      143280 non-null object
year_measured    96411 non-null float64
value            96411 non-null float64
dtypes: float64(2), object(5)
memory usage: 7.7+ MB

### PROBLEMS

1. Explore the `variable` and `variable_full` columns.  
2. How many countries are in the data?
3. How many different time periods is data recorded on?
4. How many `total_area` values are missing from the `variable` column?

### Examining Slices

- Slice by time
- Slide by Country
- Slice by Variable

In [48]:
def variable_slice(df, variable):
    
    # Only data for that variable
    df = df[df.variable==variable]
    
    # Get variable for each country over the time periods 
    df = df.pivot(index='country', columns='time_period', values='value')
    return df

In [49]:
variable_slice(data, 'total_pop').head()

time_period,1958-1962,1963-1967,1968-1972,1973-1977,1978-1982,1983-1987,1988-1992,1993-1997,1998-2002,2003-2007,2008-2012,2013-2017
country,,,,,,,,,,,,
Afghanistan,9344.00,10369.00,11717.00,13056.00,12667.00,11338.00,13746.0,18034.00,21487.00,25878.00,29727.00,32527.00
Albania,1738.00,1999.00,2254.00,2518.00,2788.00,3121.00,3241.0,3092.00,3123.00,3011.00,2881.00,2897.00
Algeria,11690.00,13354.00,15377.00,17690.00,20576.00,23918.00,27181.0,29888.00,31990.00,34262.00,37439.00,39667.00
Andorra,15.38,20.75,26.89,32.77,39.11,48.46,58.9,64.15,71.05,84.88,79.32,70.47
Angola,5466.00,5963.00,6588.00,7501.00,8808.00,10286.00,11849.0,13802.00,16110.00,19184.00,22686.00,25022.00

In [44]:
simple_regions ={
    'World | Asia':'Asia',
    'Americas | Central America and Caribbean | Central America': 'North America',
    'Americas | Central America and Caribbean | Greater Antilles': 'North America',
    'Americas | Central America and Caribbean | Lesser Antilles and Bahamas': 'North America',
    'Americas | Northern America | Northern America': 'North America',
    'Americas | Northern America | Mexico': 'North America',
    'Americas | Southern America | Guyana':'South America',
    'Americas | Southern America | Andean':'South America',
    'Americas | Southern America | Brazil':'South America',
    'Americas | Southern America | Southern America':'South America', 
    'World | Africa':'Africa',
    'World | Europe':'Europe', 
    'World | Oceania':'Oceania'
}

In [45]:
data.region = data.region.apply(lambda x: simple_regions[x])

In [6]:
import pandas_profiling as pp

In [8]:
pp.ProfileReport(data)

In [10]:
data.time_period.unique()

array(['1958-1962', '1963-1967', '1968-1972', '1973-1977', '1978-1982',
       '1983-1987', '1988-1992', '1993-1997', '1998-2002', '2003-2007',
       '2008-2012', '2013-2017'], dtype=object)

In [11]:
times = data.time_period.unique()

In [15]:
times[3]

'1973-1977'

In [38]:
data[(data.time_period == times[3])].pivot(index = 'country', columns = 'variable')

                                                                                      region  \
variable                                                                      accounted_flow
country
Afghanistan                                                                     World | Asia
Albania                                                                       World | Europe
Algeria                                                                       World | Africa
Andorra                                                                       World | Europe
Angola                                                                        World | Africa
Antigua and Barbuda                        Americas | Central America and Caribbean | Les...
Argentina                                     Americas | Southern America | Southern America
Armenia                                                                         World | Asia
Australia                                                                    World | Oceania
Austria                                                                       World | Europe
Azerbaijan                                                                      World | Asia
Bahamas                                    Americas | Central America and Caribbean | Les...
Bahrain                                                                         World | Asia
Bangladesh                                                                      World | Asia
Barbados                                   Americas | Central America and Caribbean | Les...
Belarus                                                                       World | Europe
Belgium                                                                       World | Europe
Belize                                     Americas | Central America and Caribbean | Cen...
Benin                                                                         World | Africa
Bhutan                                                                          World | Asia
Bolivia (Plurinational State of)                        Americas | Southern America | Andean
Bosnia and Herzegovina                                                        World | Europe
Botswana                                                                      World | Africa
Brazil                                                  Americas | Southern America | Brazil
Brunei Darussalam                                                               World | Asia
Bulgaria                                                                      World | Europe
Burkina Faso                                                                  World | Africa
Burundi                                                                       World | Africa
Cabo Verde                                                                    World | Africa
Cambodia                                                                        World | Asia
...                                                                                      ...
Swaziland                                                                     World | Africa
Sweden                                                                        World | Europe
Switzerland                                                                   World | Europe
Syrian Arab Republic                                                            World | Asia
Tajikistan                                                                      World | Asia
Thailand                                                                        World | Asia
The former Yugoslav Republic of Macedonia                                     World | Europe
Timor-Leste                                                                     World | Asia
Togo                                                                          World | Africa
Tokelau                                                                      World | Oceania
Tonga                                                                        World | Oceania
Trinidad and Tobago                        Americas | Central America and Caribbean | Les...
Tunisia                                                                       World | Africa
Turkey                                                                          World | Asia
Turkmenistan                                                                    World | Asia
Tuvalu                                                                       World | Oceania
Uganda                                                                        World | Africa
Ukraine                                                                       World | Europe
United Arab Emirates                                                            World | Asia
United Kingdom                                                                World | Europe
United Republic of Tanzania                                                   World | Africa
United States of America                      Americas | Northern America | Northern America
Uruguay                                       Americas | Southern America | Southern America
Uzbekistan                                                                      World | Asia
Vanuatu                                                                      World | Oceania
Venezuela (Bolivarian Republic of)                      Americas | Southern America | Andean
Viet Nam                                                                        World | Asia
Yemen                                                                           World | Asia
Zambia                                                                        World | Africa
Zimbabwe                                                                      World | Africa

                                                                                              \
variable                                                        accounted_flow_border_rivers
country
Afghanistan                                                                     World | Asia
Albania                                                                       World | Europe
Algeria                                                                       World | Africa
Andorra                                                                       World | Europe
Angola                                                                        World | Africa
Antigua and Barbuda                        Americas | Central America and Caribbean | Les...
Argentina                                     Americas | Southern America | Southern America
Armenia                                                                         World | Asia
Australia                                                                    World | Oceania
Austria                                                                       World | Europe
Azerbaijan                                                                      World | Asia
Bahamas                                    Americas | Central America and Caribbean | Les...
Bahrain                                                                         World | Asia
Bangladesh                                                                      World | Asia
Barbados                                   Americas | Central America and Caribbean | Les...
Belarus                                                                       World | Europe
Belgium                                                                       World | Europe
Belize                                     Americas | Central America and Caribbean | Cen...
Benin                                                                         World | Africa
Bhutan                                                                          World | Asia
Bolivia (Plurinational State of)                        Americas | Southern America | Andean
Bosnia and Herzegovina                                                        World | Europe
Botswana                                                                      World | Africa
Brazil                                                  Americas | Southern America | Brazil
Brunei Darussalam                                                               World | Asia
Bulgaria                                                                      World | Europe
Burkina Faso                                                                  World | Africa
Burundi                                                                       World | Africa
Cabo Verde                                                                    World | Africa
Cambodia                                                                        World | Asia
...                                                                                      ...
Swaziland                                                                     World | Africa
Sweden                                                                        World | Europe
Switzerland                                                                   World | Europe
Syrian Arab Republic                                                            World | Asia
Tajikistan                                                                      World | Asia
Thailand                                                                        World | Asia
The former Yugoslav Republic of Macedonia                                     World | Europe
Timor-Leste                                                                     World | Asia
Togo                                                                          World | Africa
Tokelau                                                                      World | Oceania
Tonga                                                                        World | Oceania
Trinidad and Tobago                        Americas | Central America and Caribbean | Les...
Tunisia                                                                       World | Africa
Turkey                                                                          World | Asia
Turkmenistan                                                                    World | Asia
Tuvalu                                                                       World | Oceania
Uganda                                                                        World | Africa
Ukraine                                                                       World | Europe
United Arab Emirates                                                            World | Asia
United Kingdom                                                                World | Europe
United Republic of Tanzania                                                   World | Africa
United States of America                      Americas | Northern America | Northern America
Uruguay                                       Americas | Southern America | Southern America
Uzbekistan                                                                      World | Asia
Vanuatu                                                                      World | Oceania
Venezuela (Bolivarian Republic of)                      Americas | Southern America | Andean
Viet Nam                                                                        World | Asia
Yemen                                                                           World | Asia
Zambia                                                                        World | Africa
Zimbabwe                                                                      World | Africa

                                                                                              \
variable                                                                          agg_to_gdp
country
Afghanistan                                                                     World | Asia
Albania                                                                       World | Europe
Algeria                                                                       World | Africa
Andorra                                                                       World | Europe
Angola                                                                        World | Africa
Antigua and Barbuda                        Americas | Central America and Caribbean | Les...
Argentina                                     Americas | Southern America | Southern America
Armenia                                                                         World | Asia
Australia                                                                    World | Oceania
Austria                                                                       World | Europe
Azerbaijan                                                                      World | Asia
Bahamas                                    Americas | Central America and Caribbean | Les...
Bahrain                                                                         World | Asia
Bangladesh                                                                      World | Asia
Barbados                                   Americas | Central America and Caribbean | Les...
Belarus                                                                       World | Europe
Belgium                                                                       World | Europe
Belize                                     Americas | Central America and Caribbean | Cen...
Benin                                                                         World | Africa
Bhutan                                                                          World | Asia
Bolivia (Plurinational State of)                        Americas | Southern America | Andean
Bosnia and Herzegovina                                                        World | Europe
Botswana                                                                      World | Africa
Brazil                                                  Americas | Southern America | Brazil
Brunei Darussalam                                                               World | Asia
Bulgaria                                                                      World | Europe
Burkina Faso                                                                  World | Africa
Burundi                                                                       World | Africa
Cabo Verde                                                                    World | Africa
Cambodia                                                                        World | Asia
...                                                                                      ...
Swaziland                                                                     World | Africa
Sweden                                                                        World | Europe
Switzerland                                                                   World | Europe
Syrian Arab Republic                                                            World | Asia
Tajikistan                                                                      World | Asia
Thailand                                                                        World | Asia
The former Yugoslav Republic of Macedonia                                     World | Europe
Timor-Leste                                                                     World | Asia
Togo                                                                          World | Africa
Tokelau                                                                      World | Oceania
Tonga                                                                        World | Oceania
Trinidad and Tobago                        Americas | Central America and Caribbean | Les...
Tunisia                                                                       World | Africa
Turkey                                                                          World | Asia
Turkmenistan                                                                    World | Asia
Tuvalu                                                                       World | Oceania
Uganda                                                                        World | Africa
Ukraine                                                                       World | Europe
United Arab Emirates                                                            World | Asia
United Kingdom                                                                World | Europe
United Republic of Tanzania                                                   World | Africa
United States of America                      Americas | Northern America | Northern America
Uruguay                                       Americas | Southern America | Southern America
Uzbekistan                                                                      World | Asia
Vanuatu                                                                      World | Oceania
Venezuela (Bolivarian Republic of)                      Americas | Southern America | Andean
Viet Nam                                                                        World | Asia
Yemen                                                                           World | Asia
Zambia                                                                        World | Africa
Zimbabwe                                                                      World | Africa

                                                                                              \
variable                                                                         arable_land
country
Afghanistan                                                                     World | Asia
Albania                                                                       World | Europe
Algeria                                                                       World | Africa
Andorra                                                                       World | Europe
Angola                                                                        World | Africa
Antigua and Barbuda                        Americas | Central America and Caribbean | Les...
Argentina                                     Americas | Southern America | Southern America
Armenia                                                                         World | Asia
Australia                                                                    World | Oceania
Austria                                                                       World | Europe
Azerbaijan                                                                      World | Asia
Bahamas                                    Americas | Central America and Caribbean | Les...
Bahrain                                                                         World | Asia
Bangladesh                                                                      World | Asia
Barbados                                   Americas | Central America and Caribbean | Les...
Belarus                                                                       World | Europe
Belgium                                                                       World | Europe
Belize                                     Americas | Central America and Caribbean | Cen...
Benin                                                                         World | Africa
Bhutan                                                                          World | Asia
Bolivia (Plurinational State of)                        Americas | Southern America | Andean
Bosnia and Herzegovina                                                        World | Europe
Botswana                                                                      World | Africa

In [ ]:
data[(data.time_period == times[3]) & (data.country == 'Afghanistan')].pivot

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143280 entries, 0 to 143279
Data columns (total 7 columns):
country          143280 non-null object
region           143280 non-null object
variable         143280 non-null object
variable_full    143280 non-null object
time_period      143280 non-null object
year_measured    96411 non-null float64
value            96411 non-null float64
dtypes: float64(2), object(5)
memory usage: 7.7+ MB

In [34]:
pd.pivot?

In [39]:
data.to_csv('data/eda_data/aquastat.csv')